name: CI
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    tests:
        name: Run test suite
        runs-on: ubuntu-latest

        steps:
            - name: Check out code
              uses: actions/checkout@v3

            - name: Cache node_modules
              uses: actions/cache@v4
              with:
                  path: node_modules
                  key: node_modules-${{ hashFiles('package-lock.json') }}-${{ runner.os }}

            - name: Install dependencies
              uses: ./.github/docker-run/