name: CI
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    tests:
        name: Run test suite
        runs-on: ubuntu-latest

        steps:
            - name: Check out code
              uses: actions/checkout@v3

            - name: Cache node_modules
              uses: actions/cache@v4
              with:
                  path: node_modules
                  key: node_modules-${{ hashFiles('package-lock.json') }}-${{ runner.os }}

            - name: Build Docker image
              run: docker build . -t ci-container -f .devcontainer/Dockerfile

            - name: Install dependencies
              run: docker run -w /workspace -v.:/workspace ci-container npm ci

            - name: Run CI checks
              run: docker run --init -w /workspace -v.:/workspace ci-container xvfb-run npm run check
